<footer>
    <div class='footer'>
    <div class='container'>
        <!-- Top links -->
        <div class='top-links'>
        <div class='us'>
            <div class='footer-logo'>
                <a href='index.php'><img src='./images/HerbariumLogo.PNG' alt=''></a>
                <span>Professional Botanist for You</span>
            </div>
            <div class='media'>
                <span>Follow us</span>
                <br>
                <div class='media-img'>
                    <a href='https://youtu.be/I18yanQlevE'><img src='./images/youtube-logo.png' alt=''></a>
                    <a href='https://www.instagram.com/plantnet?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=='><img src='./images/instagram.png' alt=''></a>
                    <a href='https://www.facebook.com/PictureThisAI'><img src='./images/facebook.png' alt='facebook'></a>
                    <a href='https://www.tiktok.com/@ayusyifapf/video/7277811126505622790?is_from_webapp=1&sender_device=pc&web_id=7415499129411995157'><img src='./images/tik-tok.png' alt=''></a>
                </div>
            </div>
        </div>
        </div>
        
        <!-- Categories links -->
        <div class='categories-links'>
            <span>Categories</span>
            <br>
            <ul class='categories-links-list'>
                <li><a href='classify.php'>Plant Classification</a></li>
                <li><a href='diyspecimen.php'>Herbarium Tutorial</a></li>
                <li><a href='contribute.php'>Contribute your First Plant</a></li>
                <li><a href='identify.php'>Identify a Plant</a></li>
                <li><a href='enquiry.php'>Contact us</a></li>
            </ul>
        </div>
        <!-- Extra Links -->
        <div class='extra-links'>
            <span>Extra You Can</span>
            <br>
            <ul class='extra-links-list'>
                <li><a href='enhancement.php'>Enhancements</a></li>
                <li><a href='enquiry.php'>Feedback</a></li>
                <li><a href='registration.php'>Register</a></li>
                <li><a href='login.php'>Log In</a></li>
                <li><a href='acknowledgement.php'>Acknowledgement</a></li>
            </ul>
        </div>

        <!-- Help & Support Links -->
        <div class='help-links'>
            <span>Help & Support</span>
            <br>
            <ul class='help-links-list'>
                <li><a href='https://www.swinburne.edu.my/study/visit-us/our-location.php'>Venue: <br>
                Swinburne University of Technology,<br> Kuching, Sarawak.</a></li>
                <li><a href='mailto:support@herbariumuniversal.com?subject=SupportRequest&body=Pleasedescribeyourissue:'>Contact us: <br>
                support@herbariumuniversal.com
                </a></li>
            </ul>
        </div>
        
        
        </div>
    </div>
    <!-- Copyright -->
    <div class='copyright'>© Copyright | Last Review Date: 26/09/2024</div>
    </footer>