<div class='topbar'>
        <div class='container'>
            <div class='top-left-area'>
                <div class='logo'>
                    <a href='index.php'>
                        <figure>
                            <img src='./images/HerbariumLogo.PNG' alt='logo'>
                        </figure>
                    </a>
                    
                </div>
                <span>Welcome to Herbarium Universal !</span>
            
            </div>

            <div class='top-right-area rightfix'>
                    <div class='top-nav clearfix'>
                        <ul>
                            <li>
                                <a href='identify.php'>
                                    <figure>
                                        <img src='./images/search-interface-symbol.png'>
                                    </figure>
                                </a>
                            </li>
                            <li>
                                <a href='registration.php'>
                                    <figure>
                                        <img src='./images/driver-license.png'>
                                    </figure>
                                </a>
                            </li>
                        </ul>
                    </div>
            </div>

            <div class='menu'>
                    <ul class='menu-nav-list'>
                        <li><a href='index.php'>Home</a></li>
                        <li><a href='classify.php'>Plant Classification</a></li>
                        <li id='diy'>
                            <a href='diyspecimen.php'>DIY Herbarium</a>
                            <div class='diy-list'>
                                <br>
                                <a href='tutorial.php'>Tutorial</a>
                                <br>
                                <a href='tools.php'>Tools</a>
                                <br>
                                <a href='care.php'>Methods of Care</a>
                                <br>
                            </div>
                        </li>
                        <li><a href='contribute.php'>Share</a></li>
                        <li><a href='enquiry.php'>Enquiry</a></li>
                        <li><a href='aboutme.php'>About us</a></li>
                    </ul>
            </div>
        </div>      
    </div>